# Generated by Django 3.2.3 on 2023-10-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='products',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
    ]
